### ISSUE TITLE
Production.

### ISSUE THREAD

**Issue by Akinolae** [dewaleolaoye/newsapi#1]
Hi Wale does NewsApi  run in production?

**Comment by dewaleolaoye** [comment]
I didn't push the code to production, but it should work? having issues with it?

**Comment by Akinolae** [comment]
it doesn't work in production. I think it's not free

**Comment by dewaleolaoye** [comment]
Yes, it's not free but it depends. If you are using just for learning purpose where people won't visit much, it should work. 
They explain the details in their docs

**Comment by Akinolae** [comment]
It only works in development. If you'll publish you'll have to subscribe to a paid plan.
I thought it's in production, I wanted to know how you bypassed the process.

**Comment by dewaleolaoye** [comment]
Okay, I was working on React Context API then, just to see how some some things.
Can I close this issue now?

**Comment by Akinolae** [comment]
yeah bruh
